/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zheng_secondjni_NativeClass */

#ifndef _Included_com_zheng_secondjni_NativeClass
#define _Included_com_zheng_secondjni_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zheng_secondjni_NativeClass
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zheng_secondjni_NativeClass_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_zheng_secondjni_NativeClass
 * Method:    setNewString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zheng_secondjni_NativeClass_setNewString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zheng_secondjni_NativeClass
 * Method:    setStringAdd
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zheng_secondjni_NativeClass_setStringAdd
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_zheng_secondjni_NativeClass
 * Method:    setIntAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zheng_secondjni_NativeClass_setIntAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zheng_secondjni_NativeClass
 * Method:    intMethod
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_zheng_secondjni_NativeClass_intMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_zheng_secondjni_NativeClass
 * Method:    callMethod1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zheng_secondjni_NativeClass_callMethod1
  (JNIEnv *, jobject);

/*
 * Class:     com_zheng_secondjni_NativeClass
 * Method:    callMethod2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zheng_secondjni_NativeClass_callMethod2
  (JNIEnv *, jobject);

/*
 * Class:     com_zheng_secondjni_NativeClass
 * Method:    callMethod3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zheng_secondjni_NativeClass_callMethod3
  (JNIEnv *, jobject);

/*
 * Class:     com_zheng_secondjni_NativeClass
 * Method:    callMethod4
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zheng_secondjni_NativeClass_callMethod4
  (JNIEnv *, jobject);

/*
 * Class:     com_zheng_secondjni_NativeClass
 * Method:    callMethod5
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zheng_secondjni_NativeClass_callMethod5
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
